### ISSUE TITLE
n5-view crash for 2D image

### ISSUE THREAD

**Issue by kephale** [saalfeldlab/n5-utils#18]
I have a n5 with a 2D image stored in a group. When I try to run it `n5-view -i /home/kharrington/Data/SEMA/Z1217-19m/VNC/Sec04/heightSurfaces.n5/ -d level200-top`

I get the following OOB exception. Perhaps I'm missing something, but it seems like a bug to check res[2] when there are only 2 dimensions

```
N5FSReader[basePath=/home/kharrington/Data/SEMA/Z1217-19m/VNC/Sec04/heightSurfaces.n5/] : level200-top, [1.0, 1.0], [0.0, 255.0], [0.0, 0.0], Num axes: 2
axes permutation: [0, 1] -> [0, 1]
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while calling command (org.janelia.saalfeldlab.View@400cff1a): java.lang.ArrayIndexOutOfBoundsException: 2
	at picocli.CommandLine.execute(CommandLine.java:1180)
	at picocli.CommandLine.access$800(CommandLine.java:141)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1367)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1335)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1526)
	at picocli.CommandLine.call(CommandLine.java:1786)
	at picocli.CommandLine.call(CommandLine.java:1710)
	at org.janelia.saalfeldlab.View.main(View.java:499)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
	at org.janelia.saalfeldlab.View.call(View.java:422)
	at org.janelia.saalfeldlab.View.call(View.java:166)
	at picocli.CommandLine.execute(CommandLine.java:1173)
	... 8 more
```

**Comment by kephale** [comment]
https://github.com/saalfeldlab/n5-utils/pull/19 if you'd like

**Comment by axtimwalde** [comment]
Solved by https://github.com/saalfeldlab/n5-utils/pull/19 correct?
