### ISSUE TITLE
"Ragged" end blocks cause errors

### ISSUE THREAD

**Issue by clbarnes** [saalfeldlab/n5-utils#4]
If a dataset's shape is not an integer number of blocks, reading into the region of non-full blocks shows only empty data and prints errors:

```
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException
	at net.imglib2.cache.ref.SoftRefLoaderCache.get(SoftRefLoaderCache.java:111)
	at net.imglib2.cache.util.LoaderCacheAsCacheAdapter.get(LoaderCacheAsCacheAdapter.java:30)
	at net.imglib2.cache.ref.WeakRefVolatileCache.getBlocking(WeakRefVolatileCache.java:356)
	at net.imglib2.cache.ref.WeakRefVolatileCache.access$000(WeakRefVolatileCache.java:19)
	at net.imglib2.cache.ref.WeakRefVolatileCache$FetchEntry.call(WeakRefVolatileCache.java:403)
	at net.imglib2.cache.ref.WeakRefVolatileCache$FetchEntry.call(WeakRefVolatileCache.java:380)
	at net.imglib2.cache.queue.FetcherThreads$Fetcher.run(FetcherThreads.java:168)
Caused by: java.lang.ArrayIndexOutOfBoundsException

```

**Comment by axtimwalde** [comment]
Reading outside of the shape of the dataset?

**Comment by axtimwalde** [comment]
@clbarnes is this issue still there?

**Comment by clbarnes** [comment]
I think this was due to a bad export producing malformed edge blocks. I can't reproduce it on a better export, sorry for the report!
